/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrillsRouteImport } from './routes/drills'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as RitualRouteImport } from './routes/ritual'
import { Route as TrapsRouteImport } from './routes/traps'
import { Route as TopicTopicIdRouteImport } from './routes/topic.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsRoute = DrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualRoute = RitualRouteImport.update({
  id: '/ritual',
  path: '/ritual',
  getParentRoute: () => rootRouteImport,
} as any)
const TrapsRoute = TrapsRouteImport.update({
  id: '/traps',
  path: '/traps',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicIdRoute = TopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drills': typeof DrillsRoute
  '/notebook': typeof NotebookRoute
  '/ritual': typeof RitualRoute
  '/traps': typeof TrapsRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drills': typeof DrillsRoute
  '/notebook': typeof NotebookRoute
  '/ritual': typeof RitualRoute
  '/traps': typeof TrapsRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drills': typeof DrillsRoute
  '/notebook': typeof NotebookRoute
  '/ritual': typeof RitualRoute
  '/traps': typeof TrapsRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/drills' | '/notebook' | '/ritual' | '/traps' | '/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drills' | '/notebook' | '/ritual' | '/traps' | '/topic/$topicId'
  id:
    | '__root__'
    | '/'
    | '/drills'
    | '/notebook'
    | '/ritual'
    | '/traps'
    | '/topic/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrillsRoute: typeof DrillsRoute
  NotebookRoute: typeof NotebookRoute
  RitualRoute: typeof RitualRoute
  TrapsRoute: typeof TrapsRoute
  TopicTopicIdRoute: typeof TopicTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills': {
      id: '/drills'
      path: '/drills'
      fullPath: '/drills'
      preLoaderRoute: typeof DrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritual': {
      id: '/ritual'
      path: '/ritual'
      fullPath: '/ritual'
      preLoaderRoute: typeof RitualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traps': {
      id: '/traps'
      path: '/traps'
      fullPath: '/traps'
      preLoaderRoute: typeof TrapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrillsRoute: DrillsRoute,
  NotebookRoute: NotebookRoute,
  RitualRoute: RitualRoute,
  TrapsRoute: TrapsRoute,
  TopicTopicIdRoute: TopicTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
